### ISSUE TITLE
index.js file is not found in the project

### ISSUE THREAD

**Issue by kumarz** [simonqian/react-helloworld#2]
Error: Cannot find module 'C:\Users\Kumas12\AppData\Local\Google\Cloud SDK\hello-world\flexible\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)

**Comment by simonqian** [comment]
@kumarz did you run ```npm install``` ? There seems to be no flexible folder here.

**Comment by kumarz** [comment]
@simonqian ,
I did and it didnt work as I got that exception.

**Comment by simonqian** [comment]
@kumarz can you re-download the project and try again ?
